export const Tag = {
    // General
    HEADER: 'HEAD',
    TRAILER: 'TRLR',
    CONCATENATION: 'CONC',
    CONTINUATION: 'CONT',

    // Header
    GEDCOM_FILE: 'GEDC',
    VERSION_NUMBER: 'VERS',
    GEDCOM_FORM: 'FORM',
    CHARACTER_ENCODING: 'CHAR',
    CHARACTER_ENCODING_ALT: 'CHARACTER',

    // Extension
    SOURCE: 'SOUR',
    CORPORATION: 'CORP',
    COPYRIGHT: 'COPR',
    DATA_SOURCE: 'DATA',
    LANGUAGE: 'LANG',
    SUBMITTER: 'SUBM',
    FILE_NAME: 'FILE',
    DESTINATION_SYSTEM: 'DEST',

    // Common
    NAME: 'NAME',
    DATE: 'DATE',
    TIME: 'TIME',
    NOTE: 'NOTE',
    ADDRESS: 'ADDR',
    ADDRESS_1: 'ADR1',
    ADDRESS_2: 'ADR2',
    ADDRESS_3: 'ADR3',
    CITY: 'CITY',
    STATE: 'STAE',
    POSTAL_CODE: 'POST',
    COUNTRY: 'CTRY',
    PHONE_NUMBER: 'PHON',
    EMAIL_ADDRESS: 'EMAIL',
    FAX_ADDRESS: 'FAX',
    WEB_ADDRESS: 'WWW',


    // Records
    EVENT: 'EVEN',
    TYPE: 'TYPE',
    PLACE: 'PLAC',

    INDIVIDUAL: 'INDI',
    FAMILY: 'FAM',

    HUSBAND: 'HUSB',
    WIFE: 'WIFE',
    CHILD: 'CHIL',
    CHILDREN_COUNT: 'NCHI',
    REFERENCE_NUMBER: 'REFN',
    AGE: 'AGE',
    ANNULMENT: 'ANUL',

    PHONETIC: 'FONE',
    ROMANISED: 'ROMN',
    MAP: 'MAP',
    LATITUDE: 'LATI',
    LONGITUDE: 'LONG',

    NAME_PREFIX: 'NPFX',
    NAME_GIVEN: 'GIVN',
    NAME_NICK: 'NICK',
    SURNAME_PREFIX: 'SPFX',
    SURNAME: 'SURN',
    SURNAME_SUFFIX: 'NSFX',

    SEX: 'SEX'
}
