export enum ValueMultimediaFormat {
    Aac = 'AAC',
    Avi = 'AVI',
    Bmp = 'BMP',
    Epub = 'ePUB',
    Flac = 'FLAC',
    Gif = 'GIF',
    Jpeg = 'JPEG',
    Jpg = 'JPG',
    Mkv = 'MKV',
    Mobi = 'mobi',
    Mp3 = 'MP3',
    Pcx = 'PCX',
    Pdf = 'PDF',
    Png = 'PNG',
    Tiff = 'TIFF',
    Tif = 'TIF',
    Wav = 'WAV',
}
